[package]
name = "petra"
version = "2.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Programmable Engine for Telemetry, Runtime, and Automation"

[dependencies]
# Core runtime - minimal features only
tokio = { version = "1.40", features = ["rt-multi-thread", "time", "signal", "macros", "sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"

# Essential concurrency
dashmap = "6.0"
crossbeam = "0.8"
parking_lot = "0.12"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging - minimal
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"], default-features = false }

# MQTT - production ready
rumqttc = { version = "0.24", default-features = false, features = ["use-rustls"] }

# CLI
clap = { version = "4.5", features = ["std", "derive"] }

# Time handling
chrono = { version = "0.4.38", features = ["serde"], default-features = false }

# Core utilities
bytes = "1.5"
ringbuffer = "0.15"
async-trait = "0.1"
regex = "1.10"
base64 = "0.22"
htmlescape = "0.3"

# S7 communication (only if needed)
rust-snap7 = { version = "1.142.2", optional = true }

# HTTP client - minimal features
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false, optional = true }

# Metrics - lightweight
metrics = { version = "0.23", default-features = false, optional = true }
metrics-exporter-prometheus = { version = "0.15", default-features = false, optional = true }

# Storage - all optional for production flexibility
arrow = { version = "55.1", default-features = false, optional = true }
parquet = { version = "55.1", default-features = false, optional = true }
rocksdb = { version = "0.21", default-features = false, optional = true }
clickhouse = { version = "0.12", default-features = false, features = ["lz4"], optional = true }

# Cloud storage (optional)
object_store = { version = "0.7", default-features = false, optional = true }
aws-sdk-s3 = { version = "0.31", default-features = false, optional = true }
aws-config = { version = "0.56", default-features = false, optional = true }

# Compression (optional)
zstd = { version = "0.12", default-features = false, optional = true }
lz4 = { version = "1.24", default-features = false, optional = true }

# Security (optional)
ring = { version = "0.17", default-features = false, optional = true }
rustls = { version = "0.23", default-features = false, optional = true }
rustls-pemfile = { version = "2", default-features = false, optional = true }

# Protocol support (optional)
opcua = { version = "0.12", default-features = false, optional = true }
tokio-modbus = { version = "0.7", default-features = false, optional = true }

# Development/debugging (optional)
csv = { version = "1.3", optional = true }
schemars = { version = "0.8", default-features = false, optional = true }
jsonschema = { version = "0.18", default-features = false, optional = true }

# GUI dependencies (optional, for dashboard)
eframe = { version = "0.30", optional = true }
egui_plot = { version = "0.30", optional = true }

# Utilities
rand = { version = "0.8", optional = true }

[dev-dependencies]
criterion = { version = "0.5", default-features = false }
proptest = "1.4"
tokio-test = "0.4"


[features]
# Minimal default for fast builds
default = ["standard-monitoring"]
standard-monitoring = []
enhanced-monitoring = ["standard-monitoring", "dep:ringbuffer"]
full = ["enhanced-monitoring", "advanced-storage", "metrics"]
# Optional heavy features
advanced-storage = ["rocksdb", "clickhouse", "object_store", "aws-sdk-s3", "aws-config", "zstd", "lz4"]
metrics = ["dep:metrics", "metrics-exporter-prometheus"]
web = ["reqwest"]
security = ["ring", "rustls", "rustls-pemfile"]
opcua-support = ["opcua"]
modbus-support = ["tokio-modbus"]
json-schema = ["schemars", "jsonschema"]

# Development features
[[bin]]
name = "petra"
path = "src/main.rs"

[[bin]]
name = "s7_test"
path = "src/bin/s7_test.rs"
required-features = ["s7-support"]

[[bin]]
name = "mqtt_publisher"
path = "src/bin/mqtt_publisher.rs"
required-features = ["examples"]

[[bin]]
name = "petra_dashboard"
path = "src/bin/dashboard.rs"
required-features = ["gui", "history"]

[[bin]]
name = "parquet_viewer"
path = "src/bin/parquet_viewer.rs"
required-features = ["history"]

[[bin]]
name = "storage_test"
path = "src/bin/storage_test.rs"
required-features = ["history"]

[[bin]]
name = "twilio_test"
path = "src/bin/twilio_test.rs"
required-features = ["web"]

[[bin]]
name = "simple_s7_test"
path = "src/bin/simple_s7_test.rs"
required-features = ["s7-support"]

[[bin]]
name = "generate_schema"
path = "src/bin/generate_schema.rs"
required-features = ["json-schema"]

[profile.release]
# Balanced for production: reasonable build time + performance
lto = "thin"          # Faster than "fat", still optimized
codegen-units = 4     # Faster than 1, still well optimized
panic = "abort"
strip = true          # Remove debug symbols
