[package]
name = "petra"
version = "2.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["rt-multi-thread", "time", "signal", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
dashmap = "6.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rumqttc = "0.24"
chrono = "0.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
