[package]
name = "petra"
version = "2.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "Programmable Engine for Telemetry, Runtime, and Automation with S7 PLC support"

[dependencies]
tokio = { version = "1.40", features = ["rt-multi-thread", "time", "signal", "macros", "sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
dashmap = "6.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rumqttc = "0.24"
chrono = "0.4"
# S7 communication library - using rust-snap7
rust-snap7 = "1.142.2"
clap = { version = "4", features = ["derive"] }
# HTTP client for Twilio API
reqwest = { version = "0.11", features = ["json"] }
# Base64 encoding for auth
base64 = "0.21"
# URL encoding
urlencoding = "2.1"
# HTML encoding for TwiML
htmlescape = "0.3"
# Metrics
influxdb3-client = "0.1"
prometheus = "0.13"
metrics = "0.23"
metrics-exporter-prometheus = "0.15"
bytes = "1.5"
crossbeam = "0.8"
ringbuffer = "0.15"
parking_lot = "0.12"
[[bin]]
name = "petra"
path = "src/main.rs"

[[bin]]
name = "s7_test"
path = "src/bin/s7_test.rs"

[[bin]]
name = "simple_s7_test"
path = "src/bin/simple_s7_test.rs"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[features]
default = ["s7-support"]
s7-support = []

[[bin]]
name = "twilio_test"
path = "src/bin/twilio_test.rs"
