[package]
name = "petra"
version = "2.0.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
tokio = { version = "1.40", features = ["rt-multi-thread", "time", "signal", "macros", "sync"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
dashmap = "6.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rumqttc = "0.24"
chrono = "0.4"
# License management
ed25519-dalek = "2.1"
sha2 = "0.10"
bincode = "1.3"
base64 = "0.22"
libloading = "0.8"
# Hardware fingerprinting
sysinfo = "0.31"
mac_address = "1.1"

[features]
default = []
connectors = ["libloading"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
