# docker-compose.yml
# Main production Docker Compose file for Petra
version: '3.8'

services:
  petra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petra
    restart: unless-stopped
    ports:
      - "9090:9090"      # Metrics endpoint
      - "8080:8080"      # Health API endpoint
    volumes:
      - ./configs:/app/configs:ro
      - petra-data:/data
    environment:
      - RUST_LOG=petra=info
      - PETRA_CONFIG=/app/configs/production.yaml
    depends_on:
      - clickhouse
      - mqtt
    networks:
      - petra-network
    healthcheck:
      test: ["CMD", "/usr/local/bin/petra", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: petra-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"      # HTTP interface
      - "9000:9000"      # Native TCP protocol
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=petra
      - CLICKHOUSE_PASSWORD=secure_password
      - CLICKHOUSE_DB=petra_history
    networks:
      - petra-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: petra-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"      # MQTT protocol
      - "9001:9001"      # WebSocket
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mqtt-data:/mosquitto/data
      - mqtt-logs:/mosquitto/log
    networks:
      - petra-network
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "health_check"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  petra-data:
    driver: local
  clickhouse-data:
    driver: local
  clickhouse-logs:
    driver: local
  mqtt-data:
    driver: local
  mqtt-logs:
    driver: local

networks:
  petra-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
