apiVersion: v1
kind: ConfigMap
metadata:
  name: petra-config
  namespace: petra
data:
  config.yaml: |
    signals:
      - name: k8s_health
        type: bool
        initial: true
        
    mqtt:
      broker_host: mosquitto-service
      broker_port: 1883
      client_id: petra-k8s
      
    scan_time_ms: 100
