apiVersion: v1
kind: Service
metadata:
  name: petra-service
  namespace: petra
  labels:
    app: petra
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: petra
