# Hello Petra - Simplest possible configuration
# This config creates a counter that increments every second

signals:
  - name: counter
    type: int
    initial: 0
    description: "Simple counter signal"
    
  - name: increment
    type: bool
    initial: true
    description: "Always true to trigger increment"

blocks:
  - name: counter_increment
    type: Counter
    inputs:
      enable: increment
      reset: false
    outputs:
      count: counter
    params:
      increment: 1
      
# Optional: See the counter value
mqtt:
  broker_host: localhost
  broker_port: 1883
  client_id: hello-petra
  publish:
    - signal: counter
      topic: petra/counter
      interval_ms: 1000

scan_time_ms: 1000  # Run logic once per second
