# Petra Automation Engine Configuration
scan_time_ms: 100

# Signal definitions
signals:
  - name: "input_1"
    type: "bool"
    initial: false
    description: "Digital input 1"
    
  - name: "input_2" 
    type: "bool"
    initial: false
    description: "Digital input 2"
    
  - name: "output_1"
    type: "bool"
    initial: false
    description: "Digital output 1"
    
  - name: "analog_input_1"
    type: "float"
    initial: 0.0
    description: "Analog input 1"
    unit: "V"
    min: 0.0
    max: 10.0
    
  - name: "counter_value"
    type: "int"
    initial: 0
    description: "Counter value"

# Logic blocks
blocks:
  - name: "and_gate_1"
    type: "AND"
    inputs:
      input1: "input_1"
      input2: "input_2"
    outputs:
      output: "output_1"
    description: "Simple AND gate"
    
  - name: "counter_1"
    type: "Counter"
    inputs:
      enable: "input_1"
      reset: "input_2"
    outputs:
      count: "counter_value"
    params:
      max_count: 1000
      
  - name: "timer_1"
    type: "Timer"
    inputs:
      trigger: "output_1"
    outputs:
      elapsed: "timer_elapsed"
    params:
      duration_ms: 5000

# Metrics configuration
metrics:
  enabled: true
  bind_address: "0.0.0.0:9090"
  path: "/metrics"
  timeout_secs: 30

# Metadata
metadata:
  version: "1.0.0"
  description: "Sample Petra configuration"
  author: "Automation Engineer"
