signals:
  - name: system_pressure
    type: float
    initial: 100.0
  - name: low_pressure_setpoint
    type: float
    initial: 55.0
  - name: pressure_alarm
    type: bool
    initial: false
  - name: alarm_active
    type: bool
    initial: false

blocks:
  # Compare pressure to setpoint
  - name: low_pressure_check
    type: LT
    inputs:
      in1: system_pressure
      in2: low_pressure_setpoint
    outputs:
      out: pressure_alarm
  
  # Add 10 second delay to prevent false alarms
  - name: alarm_delay
    type: TON
    inputs:
      in: pressure_alarm
    outputs:
      q: alarm_active
    params:
      preset_ms: 10000

scan_time_ms: 100

# MQTT configuration to read pressure from external sensor
mqtt:
  broker_host: mqtt.lithos.systems
  broker_port: 1883
  client_id: petra-pressure-monitor
  topic_prefix: petra/alarm
  publish_on_change: true
  subscriptions:
    # Subscribe to external pressure sensor
    - topic: sensors/pressure/value
      signal: system_pressure
      data_type: float
    # Or if the sensor publishes JSON
    - topic: sensors/pressure/json
      signal: system_pressure
      data_type: float
      value_path: pressure.value

# Twilio configuration for alerts
twilio:
  from_number: "+1987654321"
  actions:
    - name: low_pressure_alert
      trigger_signal: alarm_active
      action_type: call
      to_number: "+18323127224"
      content: |
        <Response>
          <Say voice="alice">
            Alert: Low system pressure detected.
            Current pressure is below 55 PSI.
            Please check the system immediately.
          </Say>
        </Response>
      cooldown_seconds: 300
