# configs/docker-example.yaml
signals:
  - name: "demo_counter"
    type: "int"
    initial: 0
  
  - name: "temperature"
    type: "float"
    initial: 20.0
  
  - name: "system_status"
    type: "bool"
    initial: true

blocks:
  - name: "counter"
    type: "COUNTER"
    inputs:
      enable: "system_status"
    outputs:
      count: "demo_counter"
    params:
      increment: 1
      
  - name: "temp_simulator"
    type: "DATA_GENERATOR"
    inputs:
      enable: "system_status"
    outputs:
      sine_out: "temperature"
    params:
      frequency: 0.1
      amplitude: 10.0
      offset: 20.0

scan_time_ms: 1000

mqtt:
  broker_host: "${MQTT_HOST:-mosquitto}"
  broker_port: 1883
  client_id: "petra-docker"
  topic_prefix: "petra/demo"
  publish_on_change: true

storage:
  strategy: "local_first"
  local:
    data_dir: "/app/data/local"
    max_file_size_mb: 100
    compression: "zstd"
  remote:
    type: "clickhouse"
    url: "http://${CLICKHOUSE_HOST:-clickhouse}:8123"
    database: "petra_timeseries"
    username: "${CLICKHOUSE_USER:-petra}"
    password: "${CLICKHOUSE_PASSWORD}"
    batch_size: 1000
