# Updated Petra PLC configuration for independent Node-RED deployment
signals:
  - name: "start_button"
    type: "bool"
    initial: false

  - name: "stop_button"
    type: "bool"
    initial: false

  - name: "emergency_stop"
    type: "bool"
    initial: false

  - name: "motor_run"
    type: "bool"
    initial: false

  - name: "motor_enabled"
    type: "bool"
    initial: false

  - name: "start_pulse"
    type: "bool"
    initial: false

  - name: "motor_speed"
    type: "int"
    initial: 0

  - name: "temperature"
    type: "float"
    initial: 20.0

  - name: "temp_limit"
    type: "float"
    initial: 75.0

  - name: "over_temp"
    type: "bool"
    initial: false

  - name: "temp_ok_signal"
    type: "bool"
    initial: true

  - name: "system_healthy"
    type: "bool"
    initial: true

blocks:
  - name: "start_trigger"
    type: "R_TRIG"
    inputs:
      clk: "start_button"
    outputs:
      q: "start_pulse"

  - name: "motor_latch"
    type: "SR_LATCH"
    inputs:
      set: "start_pulse"
      reset: "stop_button"
    outputs:
      q: "motor_enabled"

  - name: "emergency_reset"
    type: "NOT"
    inputs:
      in: "emergency_stop"
    outputs:
      out: "emergency_ok"

  - name: "temp_check"
    type: "GT"
    inputs:
      in1: "temperature"
      in2: "temp_limit"
    outputs:
      out: "over_temp"

  - name: "temp_ok"
    type: "NOT"
    inputs:
      in: "over_temp"
    outputs:
      out: "temp_ok_signal"

  - name: "system_status"
    type: "AND"
    inputs:
      in1: "emergency_ok"
      in2: "temp_ok_signal"
    outputs:
      out: "system_healthy"

  - name: "motor_control"
    type: "AND"
    inputs:
      in1: "motor_enabled"
      in2: "system_healthy"
    outputs:
      out: "motor_run"

  - name: "speed_control"
    type: "TON"
    inputs:
      in: "motor_run"
    outputs:
      q: "speed_ramp_done"
    params:
      preset_ms: 2000

scan_time_ms: 100

mqtt:
  broker_host: "localhost"
  broker_port: 1883
  client_id: "petra-plc-01"
  topic_prefix: "petra/plc"
  qos: 1
  publish_on_change: true
