# Optimized minimal configuration for PETRA
# Addresses the jitter validation while providing good performance
version: "1.0"

# Optimized timing values - good balance of performance and stability
scan_time_ms: 100        # 100ms scan time for stable operation
max_scan_jitter_ms: 10   # 20% of scan time - good compromise
error_recovery: true
max_consecutive_errors: 10

signals:
  - name: "test.input"
    type: "float"
    initial: 0.0
    description: "Test input signal"
    
  - name: "test.output"
    type: "bool"
    initial: false
    description: "Test output signal"
    
  - name: "constants.threshold"
    type: "float"
    initial: 0.5
    description: "Threshold value"

blocks:
  - name: "threshold_check"
    type: "GT"
    inputs:
      in1: "test.input"
      in2: "constants.threshold"
    outputs:
      out: "test.output"
