# Minimal test configuration for debugging
# Fixed jitter validation issue
version: "1.0"

# Conservative timing values to avoid jitter validation edge cases
scan_time_ms: 100
max_scan_jitter_ms: 10  # 10% of scan time - very conservative to avoid validation issues
error_recovery: true
max_consecutive_errors: 10

signals:
  - name: "test.input"
    type: "float"
    initial: 0.0
    description: "Test input signal"
    
  - name: "test.output"
    type: "bool"
    initial: false
    description: "Test output signal"
    
  - name: "constants.threshold"
    type: "float"
    initial: 0.5
    description: "Threshold value"

blocks:
  - name: "threshold_check"
    type: "GT"
    inputs:
      in1: "test.input"
      in2: "constants.threshold"
    outputs:
      out: "test.output"
