# configs/twilio-example.yaml
signals:
  # Process monitoring
  - name: "high_temp_alarm"
    type: "bool"
    initial: false
  
  - name: "low_pressure_alarm"
    type: "bool"
    initial: false
  
  - name: "emergency_stop"
    type: "bool"
    initial: false
  
  - name: "shift_manager_notified"
    type: "bool"
    initial: false
  
  - name: "maintenance_called"
    type: "bool"
    initial: false
  
  - name: "temperature"
    type: "float"
    initial: 20.0
  
  - name: "pressure"
    type: "float"
    initial: 100.0
  
  - name: "temp_limit"
    type: "float"
    initial: 80.0
  
  - name: "pressure_limit"
    type: "float"
    initial: 50.0

blocks:
  # Process monitoring
  - name: "temp_check"
    type: "GT"
    inputs:
      in1: "temperature"
      in2: "temp_limit"
    outputs:
      out: "high_temp_alarm"
  
  - name: "pressure_check"
    type: "LT"
    inputs:
      in1: "pressure"
      in2: "pressure_limit"
    outputs:
      out: "low_pressure_alarm"
  
  # Combined alarm logic
  - name: "any_process_alarm"
    type: "OR"
    inputs:
      in1: "high_temp_alarm"
      in2: "low_pressure_alarm"
    outputs:
      out: "process_alarm"
  
  # SMS alert for shift manager
  - name: "shift_manager_sms"
    type: "TWILIO"
    inputs:
      trigger: "process_alarm"
    outputs:
      success: "shift_manager_notified"
    params:
      action_type: "sms"
      to_number: "+1234567890"  # Shift manager
      content: "Process alarm: Check system immediately. Temp: high_temp_alarm, Pressure: low_pressure_alarm"
      cooldown_ms: 300000  # 5 minutes

  # Emergency call for critical situations
  - name: "emergency_voice_call"
    type: "TWILIO"
    inputs:
      trigger: "emergency_stop"
    outputs:
      success: "maintenance_called"
    params:
      action_type: "call"
      to_number: "+1234567890"  # Maintenance on-call
      content: |
        <Response>
          <Say voice="alice"
