version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: petra-ca-db
    environment:
      POSTGRES_USER: petra
      POSTGRES_PASSWORD: petra_secure_password
      POSTGRES_DB: petra_ca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ca-service:
    build: .
    container_name: petra-ca-service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://petra:petra_secure_password@postgres:5432/petra_ca
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      FROM_EMAIL: ${FROM_EMAIL:-certificates@petra.systems}
      MQTT_BROKER_HOST: ${MQTT_BROKER_HOST:-mqtt.petra.systems}
      RUST_LOG: petra_ca_service=debug
    ports:
      - "8443:8443"
    volumes:
      - ./ca:/app/ca

volumes:
  postgres_data:
