# docker-compose.yml
version: '3.8'

services:
  petra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petra
    restart: unless-stopped
    ports:
      - "9090:9090"      # Metrics
      - "8080:8080"      # Health API
    volumes:
      - ./configs:/app/configs
      - petra-data:/data
    environment:
      - RUST_LOG=petra=info
      - PETRA_CONFIG=/app/configs/production.yaml
    depends_on:
      - clickhouse
      - mqtt
    networks:
      - petra-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: petra-clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"      # HTTP
      - "9000:9000"      # Native
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=petra
      - CLICKHOUSE_PASSWORD=secure_password
      - CLICKHOUSE_DB=petra_history
    networks:
      - petra-network

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: petra-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"      # MQTT
      - "9001:9001"      # WebSocket
    volumes:
      - ./configs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-logs:/mosquitto/log
    networks:
      - petra-network

volumes:
  petra-data:
  clickhouse-data:
  mqtt-data:
  mqtt-logs:

networks:
  petra-network:
    driver: bridge
