signals:
  - name: "temperature"
    type: "float"
    initial: 20.0
  
  - name: "pressure"
    type: "float"
    initial: 100.0
  
  - name: "motor_current"
    type: "float"
    initial: 0.0

blocks:
  # ... your blocks ...

scan_time_ms: 100

mqtt:
  broker_host: "mqtt.lithos.systems"
  broker_port: 1883
  client_id: "petra-01"
  topic_prefix: "petra/plc"

history:
  data_dir: "./data/history"
  max_file_size_mb: 100
  batch_size: 5000
  flush_interval_ms: 1000
  buffer_size: 100000
  retention_days: 30
  downsample_rules:
    - signal_pattern: "temperature"
      min_interval_ms: 1000  # Max 1 sample per second
      aggregation: "mean"
    - signal_pattern: "motor"
      min_interval_ms: 100   # Max 10 samples per second
      aggregation: "last"
